[package]
name = "kinship-net"
description = "tokio UDP and TCP driver for kinship-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
kinship-core.workspace = true

[lints]
workspace = true
