from collections.abc import Awaitable, Mapping
from datetime import timedelta
from typing import Any, Literal, final

__version__: str

_RawMember = tuple[str, str, int, int, list[tuple[str, str]]]
_RawEvent = tuple[
    str,
    _RawMember | None,
    list[tuple[str, str]] | None,
    str | None,
    int | None,
]
_Duration = float | timedelta

@final
class Config:
    """Settings for a cluster node, validated as a whole when built.

    Pick a preset with ``Config.lan()``, ``Config.wan()`` or ``Config.local()`` and override
    fields by keyword. Configs are frozen; ``replace()`` returns a changed copy. A bad value
    raises ``ConfigError``, a ``ValueError`` naming the field, before any socket opens.
    """

    def __init__(self, **fields: Any) -> None: ...
    @classmethod
    def lan(cls, **fields: Any) -> Config: ...
    @classmethod
    def wan(cls, **fields: Any) -> Config: ...
    @classmethod
    def local(cls, **fields: Any) -> Config: ...
    def replace(self, **fields: Any) -> Config: ...
    @property
    def preset(self) -> Literal["lan", "wan", "local"]: ...
    # Identity and network
    name: str
    bind: str
    advertise: str | None
    cluster: str
    seeds: list[str]
    meta: dict[str, str]
    # Security: `keys` is write-only; these are their ids.
    key_ids: list[str]
    insecure_plaintext: bool
    # Failure detection, durations in seconds
    probe_interval: float
    probe_timeout: float
    indirect_checks: int
    tcp_fallback_ping: bool
    suspicion_mult: int
    suspicion_max_mult: int
    expected_confirmations: int
    awareness_max: int
    local_health: bool
    nacks: bool
    dynamic_suspicion: bool
    buddy_system: bool
    dead_reclaim: float
    # Gossip and sync
    gossip_interval: float
    gossip_nodes: int
    gossip_to_the_dead: float
    retransmit_mult: int
    push_pull_interval: float
    reconnect_interval: float
    rejoin_interval: float
    # Limits and runtime
    udp_max_payload: int
    max_stream_frame: int
    max_meta_bytes: int
    tcp_timeout: float
    tcp_header_timeout: float
    max_inbound_streams: int
    max_inbound_streams_per_ip: int
    # None: one max_stream_frame frame and its 4-byte length prefix
    max_inbound_bytes_per_ip: int | None
    join_retries: int
    event_buffer: int
    runtime_threads: int

@final
class Node:
    @staticmethod
    def start(cfg: Config) -> Awaitable[Node]: ...
    @staticmethod
    def start_blocking(cfg: Config, timeout: float | None = None) -> Node: ...
    def join(self, seeds: list[str] | None = None) -> Awaitable[int]: ...
    def join_blocking(
        self, seeds: list[str] | None = None, timeout: float | None = None
    ) -> int: ...
    def members(self) -> list[_RawMember]: ...
    def member(self, name: str) -> _RawMember | None: ...
    def local(self) -> _RawMember: ...
    def local_addr(self) -> str: ...
    def stats(self) -> dict[str, int]: ...
    def events(self) -> EventSub: ...
    def set_meta(self, meta: Mapping[str, str]) -> Awaitable[None]: ...
    def set_meta_blocking(self, meta: Mapping[str, str], timeout: float | None = None) -> None: ...
    def update_meta(self, changes: Mapping[str, str | None]) -> Awaitable[None]: ...
    def update_meta_blocking(
        self, changes: Mapping[str, str | None], timeout: float | None = None
    ) -> None: ...
    def leave(self, timeout: float) -> Awaitable[bool]: ...
    def leave_blocking(self, timeout: float) -> bool: ...
    def close(self) -> Awaitable[None]: ...
    def close_blocking(self, timeout: float | None = None) -> None: ...
    def shutdown(self, timeout: float) -> Awaitable[bool]: ...
    def shutdown_blocking(self, timeout: float) -> bool: ...
    def is_closed(self) -> bool: ...
    def key_install(self, key: bytes | str) -> Awaitable[None]: ...
    def key_use(self, key: bytes | str) -> Awaitable[None]: ...
    def key_remove(self, key: bytes | str) -> Awaitable[None]: ...
    def key_install_blocking(self, key: bytes | str, timeout: float | None = None) -> None: ...
    def key_use_blocking(self, key: bytes | str, timeout: float | None = None) -> None: ...
    def key_remove_blocking(self, key: bytes | str, timeout: float | None = None) -> None: ...
    def key_ids(self) -> list[str]: ...

@final
class EventSub:
    def try_next(self) -> _RawEvent | None: ...
    def next(self) -> Awaitable[_RawEvent | None]: ...
    def next_blocking(self, timeout: float | None = None) -> _RawEvent | Literal[False] | None: ...

def wire_version() -> int: ...
def generate_key() -> str: ...
def route_to_python(level: int) -> None: ...
def route_to_stderr() -> None: ...
def drain_logs() -> tuple[list[tuple[int, str, str]], int]: ...
def wait_logs() -> Awaitable[None]: ...
def wait_logs_blocking(timeout: float) -> bool: ...
